### ISSUE TITLE
Buttons position are abosolute instead of relative to the canvas position.

### ISSUE THREAD

**Issue by Tain101** [cursorial/cursorial.github.io#2]
Because of the new text, the canvas is much lower down. The buttons' position are absolute so they have become misaligned with the canvas.

**Comment by cursorial** [comment]
Ahh, this is probably because my screen is wide enough that the text doesn't throw the canvas off, I'll put the text onto another page instead of having it take up that massive block, thanks for the feedback :)

**Comment by cursorial** [comment]
The instructions and changelog have been moved to their own pages now, thanks again for letting me know :)
