### ISSUE TITLE
Reduce Population Decline Rate button increases instead of decreases

### ISSUE THREAD

**Issue by Tain101** [cursorial/cursorial.github.io#3]

**Comment by cursorial** [comment]
Thanks for the feedback, I guess it's a bit unclear, but the population is multiplied by the decline rate, when it goes up, the population declines less.

e.g. 

100 * 0.95 = 95

100 * 0.99 = 99

I might add something in there to make it clearer, but for now I think it's fine as it is, thanks for the feedback.
